# Generated by Django 4.2.7 on 2026-02-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='错题标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('my_answer', models.CharField(max_length=200, verbose_name='我的答案')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='正确答案')),
                ('analysis', models.TextField(verbose_name='错题解析')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='知识点名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='error_notes.tag', verbose_name='父知识点')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_type', models.CharField(choices=[('add', '新增错题'), ('edit', '编辑错题'), ('delete', '删除错题'), ('bind_tag', '关联知识点'), ('unbind_tag', '取消关联知识点')], max_length=20, verbose_name='操作类型')),
                ('content', models.CharField(help_text='如：新增错题“列表推导式语法错误”', max_length=200, verbose_name='操作内容')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('related_error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='error_notes.errornote', verbose_name='关联错题')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-operate_time'],
            },
        ),
        migrations.AddField(
            model_name='errornote',
            name='tags',
            field=models.ManyToManyField(related_name='error_notes', to='error_notes.tag', verbose_name='关联知识点'),
        ),
    ]
